from __future__ import annotations

MODALITY_DESC_BUCKETS = {
    "T1": {
        "thin:axial": [
            "thin-slice isotropic axial T1 MRI",
            "axial T1 brain volume with thin isotropic sections",
            "axial T1-weighted brain MRI with thin isotropic slices",
            "high-resolution thin-slice isotropic axial T1 scan",
            "thin isotropic axial T1 acquisition",
        ],
        "thin:sagittal": [
            "thin-slice isotropic sagittal T1 MRI",
            "sagittal T1 brain volume with thin isotropic sections",
            "sagittal T1 brain volume with isotropic thin slices",
            "thin-slice isotropic high-resolution sagittal T1 scan",
            "thin-slice sagittal T1 acquisition with isotropic voxels",
        ],
        "thin:coronal": [
            "thin-slice isotropic coronal T1 MRI",
            "coronal T1 brain volume with thin isotropic sections",
            "coronal T1 brain scan with thin isotropic slices",
            "thin-slice isotropic high-resolution coronal T1 volume",
            "thin isotropic coronal T1 acquisition",
        ],
        "medium:axial": [
            "standard-resolution axial T1 MRI",
            "axial T1 MRI with routine slice thickness",
            "axial T1-weighted MRI at routine resolution",
            "standard axial T1 scan with routine slice thickness",
            "standard axial T1 volume at routine resolution",
        ],
        "medium:sagittal": [
            "standard-resolution sagittal T1 MRI",
            "sagittal T1 MRI with routine slice thickness",
            "sagittal T1 volume at routine resolution",
            "conventional sagittal T1 scan with standard slice thickness",
            "standard sagittal T1 volume at routine resolution",
        ],
        "medium:coronal": [
            "standard-resolution coronal T1 MRI",
            "coronal T1 MRI with routine slice thickness",
            "coronal T1 volume at routine resolution",
            "conventional coronal T1 scan with standard slice thickness",
            "standard coronal T1 volume at routine resolution",
        ],
        "thick:axial": [
            "thick-slice axial T1 MRI",
            "axial T1 MRI with thick sections",
            "axial T1 scan with thick sections",
            "thick-slab axial T1 volume, slice-averaged",
            "thick axial T1 volume, slice-averaged",
        ],
        "thick:sagittal": [
            "thick-slice sagittal T1 MRI",
            "sagittal T1 MRI with thick sections",
            "sagittal T1 scan with thick sections",
            "thick-slab sagittal T1 volume, slice-averaged",
            "thick sagittal T1 volume, slice-averaged",
        ],
        "thick:coronal": [
            "thick-slice coronal T1 MRI",
            "coronal T1 MRI with thick sections",
            "coronal T1 scan with thick sections",
            "thick-slab coronal T1 volume, slice-averaged",
            "thick coronal T1 volume, slice-averaged",
        ],
    },
    "T1c": {
        "thin:axial": [
            "thin-slice isotropic axial T1c MRI",
            "axial T1CE volume with thin isotropic sections",
            "axial T1CE scan with thin isotropic slices",
            "thin-slice isotropic high-resolution axial T1 post-contrast MRI",
            "thin-slice axial T1c acquisition with isotropic voxels",
        ],
        "thin:sagittal": [
            "thin-slice isotropic sagittal T1c MRI",
            "sagittal T1CE volume with thin isotropic sections",
            "sagittal T1CE scan at thin isotropic resolution",
            "sagittal T1 post-contrast MRI with isotropic thin slices",
            "thin isotropic sagittal T1c acquisition",
        ],
        "thin:coronal": [
            "thin-slice isotropic coronal T1c MRI",
            "coronal T1CE volume with thin isotropic sections",
            "coronal T1CE scan at thin isotropic resolution",
            "thin-slice isotropic coronal T1 post-contrast MRI",
            "thin isotropic coronal T1c acquisition",
        ],
        "medium:axial": [
            "standard-resolution axial T1c MRI",
            "axial T1CE MRI with standard slice thickness",
            "axial T1CE scan at standard resolution",
            "axial T1 post-contrast MRI with standard slice thickness",
            "conventional axial T1c volume at standard resolution",
        ],
        "medium:sagittal": [
            "standard-resolution sagittal T1c MRI",
            "sagittal T1CE MRI with standard slice thickness",
            "sagittal T1CE scan at standard resolution",
            "sagittal T1 post-contrast MRI with standard slice thickness",
            "conventionalsagittal T1c volume at standard resolution",
        ],
        "medium:coronal": [
            "standard-resolution coronal T1c MRI",
            "coronal T1CE MRI with standard slice thickness",
            "coronal T1CE scan at standard resolution",
            "coronal T1 post-contrast MRI with standard slice thickness",
            "conventionalcoronal T1c volume at standard resolution",
        ],
        "thick:axial": [
            "thick-slice axial T1c MRI",
            "axial T1CE MRI over a thick slab",
            "axial T1CE scan over a thick slab",
            "axial T1 post-contrast MRI with thick sections",
            "thick axial T1c volume, slice-averaged",
        ],
        "thick:sagittal": [
            "thick-slice sagittal T1c MRI",
            "sagittal T1CE MRI over a thick slab",
            "sagittal T1CE scan over a thick slab",
            "sagittal T1 post-contrast MRI with thick sections",
            "thick sagittal T1c volume, slice-averaged",
        ],
        "thick:coronal": [
            "thick-slice coronal T1c MRI",
            "coronal T1CE MRI over a thick slab",
            "coronal T1CE scan over a thick slab",
            "coronal T1 post-contrast MRI with thick sections",
            "thick coronal T1c volume, slice-averaged",
        ],
    },
    "T2": {
        "thin:axial": [
            "thin-slice isotropic axial T2 MRI",
            "axial T2 brain volume with thin isotropic sections",
            "axial T2-weighted volume with thin isotropic sections",
            "thin-slice isotropic axial T2 scan",
            "thin isotropic axial T2 acquisition",
        ],
        "thin:sagittal": [
            "thin-slice isotropic sagittal T2 MRI",
            "sagittal T2 brain volume with thin isotropic sections",
            "sagittal T2-weighted volume with thin isotropic sections",
            "thin-slice isotropic high-resolution sagittal T2 scan",
            "thin isotropic sagittal T2 acquisition",
        ],
        "thin:coronal": [
            "thin-slice isotropic coronal T2 MRI",
            "coronal T2 brain volume with thin isotropic sections",
            "coronal T2-weighted volume with thin isotropic sections",
            "thin-slice isotropic coronal T2 scan",
            "thin isotropic coronal T2 acquisition",
        ],
        "medium:axial": [
            "standard-resolution axial T2 MRI",
            "axial T2 MRI with routine slice thickness",
            "axial T2-weighted volume at routine resolution",
            "conventional axial T2 scan with standard slice thickness",
            "standard axial T2 volume at routine resolution",
        ],
        "medium:sagittal": [
            "standard-resolution sagittal T2 MRI",
            "sagittal T2 MRI with routine slice thickness",
            "sagittal T2-weighted scan at routine resolution",
            "conventional sagittal T2 volume with standard slice thickness",
            "standard sagittal T2 volume at routine resolution",
        ],
        "medium:coronal": [
            "standard-resolution coronal T2 MRI",
            "coronal T2 MRI with routine slice thickness",
            "coronal T2-weighted scan at routine resolution",
            "conventional coronal T2 volume with standard slice thickness",
            "standard coronal T2 volume at routine resolution",
        ],
        "thick:axial": [
            "thick-slice axial T2 MRI",
            "axial T2 MRI with thick sections",
            "axial T2-weighted volume with thick sections",
            "thick-slab axial T2 scan",
            "thick axial T2 volume, slice-averaged",
        ],
        "thick:sagittal": [
            "thick-slice sagittal T2 MRI",
            "sagittal T2 MRI with thick sections",
            "sagittal T2-weighted volume with thick sections",
            "thick-slab sagittal T2 scan",
            "thick sagittal T2 volume, slice-averaged",
        ],
        "thick:coronal": [
            "thick-slice coronal T2 MRI",
            "coronal T2 MRI with thick sections",
            "coronal T2-weighted volume with thick sections",
            "thick-slab coronal T2 scan",
            "thick coronal T2 volume, slice-averaged",
        ],
    },
    "FLAIR": {
        "thin:axial": [
            "thin-slice isotropic axial FLAIR MRI",
            "axial FLAIR brain volume with thin isotropic sections",
            "axial FLAIR brain MRI acquired with thin isotropic slices",
            "high-resolution thin-slice isotropic axial fluid-attenuated inversion recovery MRI",
            "isotropic thin-slice axial FLAIR scan",
        ],
        "thin:sagittal": [
            "thin-slice isotropic sagittal FLAIR MRI",
            "sagittal FLAIR volume with thin isotropic sections",
            "sagittal fluid-attenuated inversion recovery volume with thin isotropic slices",
            "isotropic thin-slice sagittal FLAIR scan",
            "high-resolution thin-slice sagittal FLAIR, isotropic",
        ],
        "thin:coronal": [
            "thin-slice isotropic coronal FLAIR MRI",
            "coronal FLAIR volume with thin isotropic sections",
            "coronal fluid-attenuated inversion recovery volume with isotropic thin slices",
            "high-resolution thin-slice isotropic coronal FLAIR scan",
            "thin-slice coronal FLAIR acquisition, isotropic voxels",
        ],
        "medium:axial": [
            "standard-resolution axial FLAIR MRI",
            "axial FLAIR volume with standard slice thickness",
            "axial fluid-attenuated inversion recovery scan at standard resolution",
            "axial FLAIR MRI with routine slice thickness",
            "conventional axial FLAIR volume at standard resolution",
        ],
        "medium:sagittal": [
            "standard-resolution sagittal FLAIR MRI",
            "sagittal FLAIR volume with standard slice thickness",
            "sagittal fluid-attenuated inversion recovery scan at standard resolution",
            "sagittal FLAIR MRI with routine slice thickness",
            "conventionalsagittal FLAIR volume at standard resolution",
        ],
        "medium:coronal": [
            "standard-resolution coronal FLAIR MRI",
            "coronal FLAIR volume with standard slice thickness",
            "coronal fluid-attenuated inversion recovery scan at standard resolution",
            "coronal FLAIR MRI with routine slice thickness",
            "conventional coronal FLAIR volume at standard resolution",
        ],
        "thick:axial": [
            "thick-slice axial FLAIR MRI",
            "axial FLAIR MRI with thick sections",
            "axial fluid-attenuated inversion recovery scan with thick sections",
            "axial FLAIR MRI over a thick slab",
            "thick axial FLAIR volume, slice-averaged",
        ],
        "thick:sagittal": [
            "thick-slice sagittal FLAIR MRI",
            "sagittal FLAIR MRI with thick sections",
            "sagittal fluid-attenuated inversion recovery scan with thick sections",
            "sagittal FLAIR MRI over a thick slab",
            "thick sagittal FLAIR volume, slice-averaged",
        ],
        "thick:coronal": [
            "thick-slice coronal FLAIR MRI",
            "coronal FLAIR MRI with thick sections",
            "coronal fluid-attenuated inversion recovery scan with thick sections",
            "coronal FLAIR MRI over a thick slab",
            "thick coronal FLAIR volume, slice-averaged",
        ],
    },
}
IMPERATIVE_SHELLS = [
    "Generate the {desc}.",
    "Produce the {desc}.",
    "Create the {desc}.",
    "Render the {desc}.",
    "Craft the {desc}.",
    "Synthesize the {desc}.",
]
MASK_GUIDE_TEMPLATES = [
    "Generate the {desc} based on the given tumor mask.",
    "Produce the {desc} conditioned on the provided tumor mask.",
    "Create the {desc} guided by the tumor mask.",
    "Render the {desc} using the tumor mask as guidance.",
    "Generate the {desc} following the tumor mask.",
    "Produce the {desc} from the supplied tumor mask.",
]
SR_TEMPLATES = {
    "default": [
        "Generate the {desc} from the low-resolution reference.",
        "Produce the {desc} with {out_mm} mm slices from the low-resolution {in_mm} mm input.",
        "Create the {desc} at {out_mm} mm slice thickness, reconstructing the {in_mm} mm low-resolution input.",
        "Render the {desc} from the {in_mm} mm input, recovering {out_mm} mm target slices.",
        "Generate the {desc} {method_appearance} from the low-resolution {in_mm} mm input.",
        "Produce the {desc}, restoring {out_mm} mm detail from the low-resolution {in_mm} mm acquisition.",
    ],
    "deblur": [
        "Generate the {desc} from the low-resolution blurred input.",
        "Restore the {desc} by deblurring the low-resolution input.",
        "Produce the {desc} with sharp edges from the blur-degraded input.",
        "Render the {desc} from the blurred acquisition.",
        "Create the {desc} free of blur based on the blurred low-resolution input.",
        "Reconstruct the {desc} by sharpening the blur-degraded input.",
        "Produce the {desc} with {out_mm} mm slices from the blurred low-resolution {in_mm} mm input.",
        "Create the {desc} at {out_mm} mm slice thickness, restoring the {in_mm} mm blurred input.",
        "Render the {desc} from the {in_mm} mm blurred low-resolution input, recovering {out_mm} mm target slices.",
    ],
    "dealias": [
        "Generate the {desc} free of aliasing from the undersampled low-resolution input.",
        "Reconstruct the {desc} by removing the aliasing of the undersampled acquisition.",
        "Produce the {desc} without fold-over artifacts from the undersampled input.",
        "Render the {desc} by de-aliasing the undersampled input.",
        "Create the {desc} by resolving the aliasing artifacts of the undersampled k-space input.",
        "Generate the {desc} from the uniformly undersampled reference, free of aliasing.",
        "Produce the {desc} with {out_mm} mm slices from the aliased low-resolution {in_mm} mm input.",
        "Create the {desc} at {out_mm} mm slice thickness from the {in_mm} mm aliased undersampled input.",
        "Render the {desc} from the {in_mm} mm aliased undersampled input, recovering {out_mm} mm target slices.",
    ],
}
MISSING_TEMPLATES = [
    "Generate the {desc} from the available co-registered modalities.",
    "Produce the {desc} from the other co-registered sequences of the same study.",
    "Create the {desc} using the available companion modalities.",
    "Generate the {desc} given the co-registered sibling scans, including lower-resolution acquisitions.",
    "Render the {desc} from the available multi-modal inputs.",
    "Generate the {desc} conditioned on the complementary sequences of this study.",
]
INPAINT_TEMPLATES = {
    "healthy": [
        "Generate the {desc} with the masked region filled as healthy tissue.",
        "Generate the {desc} with the masked region reconstructed as normal brain tissue.",
        "Generate the {desc}, filling the masked region with healthy tissue.",
        "Generate the {desc}, filling the masked region with undamaged brain tissue.",
        "Produce the {desc} with the masked region healed as normal-appearing brain tissue.",
    ],
    "tumor": [
        "Generate the {desc} with the masked region filled with enhancing tumor.",
        "Generate the {desc} with the masked region reconstructed as tumor.",
        "Generate the {desc}, restoring the tumor within the masked region.",
        "Produce the {desc} with the masked region reoccupied by enhancing tumor.",
        "Create the {desc}, regenerating the tumor inside the masked region.",
    ],
    "cavity": [
        "Generate the {desc} with the masked region filled as a resection cavity.",
        "Generate the {desc} with the masked region reconstructed as a necrotic resection cavity.",
        "Generate the {desc}, restoring the resection cavity within the masked region.",
        "Produce the {desc} with the masked region shaped as a post-operative cavity.",
        "Create the {desc}, leaving a resection cavity within the masked region.",
    ],
    "whole_brain": [
        "Generate the {desc} with the full brain restored from the partially acquired input.",
        "Produce the {desc} as a complete whole-brain scan, filling the truncated field of view.",
        "Create the {desc}, recovering the full field of view from the partially acquired volume.",
        "Generate the {desc} extending the narrow field of view to cover the whole brain.",
        "Render the {desc} as a full-brain volume with the missing regions reconstructed.",
        "Reconstruct the {desc} as a complete brain volume from the truncated acquisition.",
    ],
}
